# SPDX-License-Identifier: GPL-2.0
DRIVER_NAME ?= my-driver
HIDE_SELF_MODULE ?= 1
HIDE_VMAP ?= 1
HIDE_TASK ?= 1
HIDE_KGSL_STRENGTH ?= 0

ifeq ($(filter 0 1,$(HIDE_SELF_MODULE)),)
$(error HIDE_SELF_MODULE must be 0 or 1)
endif
ifeq ($(filter 0 1,$(HIDE_VMAP)),)
$(error HIDE_VMAP must be 0 or 1)
endif
ifeq ($(filter 0 1,$(HIDE_TASK)),)
$(error HIDE_TASK must be 0 or 1)
endif
ifeq ($(filter 0 1 2 3,$(HIDE_KGSL_STRENGTH)),)
$(error HIDE_KGSL_STRENGTH must be 0, 1, 2, or 3)
endif

ifneq ($(filter 2 3,$(HIDE_KGSL_STRENGTH)),)
ifeq ($(HIDE_TASK),0)
$(error HIDE_KGSL_STRENGTH >= 2 requires HIDE_TASK=1)
endif
endif

obj-m += $(DRIVER_NAME).o

$(DRIVER_NAME)-objs := \
	src/lifecycle.o \
	src/comm.o \
	src/memory.o \
	src/vfs_hijack.o \
	src/input_synth.o \
	src/sensor.o \
	src/harvest.o \
	src/hook_engine.o \
	src/uaccess_target.o \
	src/kallsym.o \
	src/hwbp.o \
	src/wxshadow.o \
	src/stealth_probe.o \
	src/arm64_decode/arm64_decode.o \
	src/arm64_decode/arm64_decode_base.o \
	src/arm64_decode/arm64_decode_branch.o \
	src/arm64_decode/arm64_decode_ldst.o \
	src/arm64_decode/arm64_decode_simd.o \
	src/arm64_decode/arm64_decode_sme.o \
	src/arm64_decode/arm64_decode_sve.o

ifneq ($(HIDE_TASK),0)
$(DRIVER_NAME)-objs += src/dirent_hide.o
endif

ifneq ($(HIDE_KGSL_STRENGTH),0)
$(DRIVER_NAME)-objs += src/stealth.o
endif

ifneq ($(HIDE_SELF_MODULE),0)
$(DRIVER_NAME)-objs += src/module_hide.o
endif

ccflags-y += -I$(src)/include
ccflags-y += -I$(src)/src
ccflags-y += -Wno-declaration-after-statement
ccflags-y += -Wno-unused-function
ccflags-y += -Wno-unused-variable

TARGET_PKG ?= "cent.tmgp.sgame"
ANON_INODE_NAME ?= "[eventpoll]"
REBOOT_MAGIC ?= 0x123456u

ccflags-y += -DKCFG_TARGET_PACKAGE='$(TARGET_PKG)'
ccflags-y += -DKCFG_DRIVER_NAME='"$(DRIVER_NAME)"'
ccflags-y += -DKCFG_ANON_INODE_NAME='$(ANON_INODE_NAME)'
ccflags-y += -DKCFG_REBOOT_MAGIC='$(REBOOT_MAGIC)'
ccflags-y += -DKCFG_HIDE_SELF_MODULE=$(HIDE_SELF_MODULE)
ccflags-y += -DKCFG_HIDE_VMAP=$(HIDE_VMAP)
ccflags-y += -DKCFG_HIDE_TASK=$(HIDE_TASK)
ccflags-y += -DKCFG_HIDE_KGSL_STRENGTH=$(HIDE_KGSL_STRENGTH)

KCFG_LOG_SILENT ?= 1
ccflags-y += -DKCFG_LOG_SILENT=$(KCFG_LOG_SILENT)
